spring:
  datasource:
    username: ${ENV_DATABASE_USERNAME}
    password: ${ENV_DATABASE_PASSWORD}
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    url: ${ENV_DATABASE_URL:jdbc:firebirdsql://localhost:3050/${project.basedir}/WARSHIPS.FDB}